export const ERROR_CODES = {
  SESSION_FULL: "SESSION_FULL",
  INVALID_NAME: "INVALID_NAME",
  INVALID_AVATAR: "INVALID_AVATAR",
  AVATAR_ALREADY_TAKEN: "AVATAR_ALREADY_TAKEN",
  INVALID_HOST_PASSWORD: "INVALID_HOST_PASSWORD",
  HOST_ALREADY_ACTIVE: "HOST_ALREADY_ACTIVE",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
  INVALID_PLAYER_TOKEN: "INVALID_PLAYER_TOKEN",
  HOST_REQUIRED: "HOST_REQUIRED",
  GAME_ALREADY_ACTIVE: "GAME_ALREADY_ACTIVE",
  NO_ACTIVE_GAME: "NO_ACTIVE_GAME",
  INVALID_GAME_TRANSITION: "INVALID_GAME_TRANSITION",
  ANSWER_ALREADY_SUBMITTED: "ANSWER_ALREADY_SUBMITTED",
  INVALID_ANSWER: "INVALID_ANSWER",
  HOST_MUST_ANSWER_FIRST: "HOST_MUST_ANSWER_FIRST",
  NOT_ENOUGH_PLAYERS: "NOT_ENOUGH_PLAYERS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
